version: "0.0.1"

services:
  app:
    container_name: next-boilerplate-dev
    image: next-boilerplate-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000
